import {
  Moon,
  SunMedium,
  LucideIcon,
  Loader2,
  PlusCircle,
  MoreVertical,
  Trash,
  Laptop,
  Palette,
  Settings,
  LayoutDashboard,
  LogOut,
  User,
  ChevronRight,
  FileText,
  Building2,
  CreditCard,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  spinner: Loader2,
  add: PlusCircle,
  ellipsis: MoreVertical,
  trash: Trash,
  logout: LogOut,
  settings: Settings,
  dashboard: LayoutDashboard,
  system: Laptop,
  theme: Palette,
  user: User,
  post: FileText,
  arrowRight: ChevronRight,
  org: Building2,
  billing: CreditCard,
};
